//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InRule.Authoring.Extensions.RuleAppFlowAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InRule.Authoring.Extensions.RuleAppFlowAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;&quot; &quot;&quot;&gt;&lt;!-- saved from url=(0014)about:internet --&gt;&lt;HTML&gt;
        ///    &lt;HEAD&gt;
        ///        &lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html;charset=UTF-8&apos;&gt;
        ///        &lt;META 
        ///content=&quot;IE=11.0000&quot; http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///
        ///&lt;META http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=11.0000&quot;&gt;      
        ///&lt;META charset=&quot;utf-8&quot;&gt;         &lt;TITLE&gt;InRule RuleApp Flow Visualizer&lt;/TITLE&gt;     
        ///
        ///&lt;STYLE&gt;
        ///    #main {
        ///	padding-left: 20px;
        ///}
        ///.treed__item {
        ///	list-style: none; border-radius: 10px; paddi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FlowVisualizer1 {
            get {
                return ResourceManager.GetString("FlowVisualizer1", resourceCulture);
            }
        }
    }
}
